"""empty message

Revision ID: 63d292bde212
Revises: 2d853cef4cd8
Create Date: 2024-02-18 00:43:42.991323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d292bde212'
down_revision = '2d853cef4cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hash', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=120), nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('salt')
        batch_op.drop_column('hash')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
